### ISSUE TITLE
Migrate to criterion

### ISSUE THREAD

**Issue by thoward27** [URI-ABD/distances#1]
Benchmarking is currently not in rust stable, nor can we find a clear roadmap that lays out when it will be. Criterion, on the other hand, is in stable and can generate some plots for us as well.

https://github.com/bheisler/criterion.rs

**Comment by thoward27** [comment]
Unassigning until this becomes a priority for us. There are much bigger fish to fry at the moment.

**Comment by nishaq503** [comment]
Done
